.TH CONSPIRE\-GTK "1" "December 2007" "conspire" "User Commands"
.SH NAME
conspire\-bot \- a high quality IRC client which has no interface
.SH DESCRIPTION
.SS "Usage:"
.IP
conspire\-bot [OPTION...]
.SS "Help Options:"
.TP
\-?, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
.SS "Application Options:"
.TP
\fB\-\-url\fR=\fIURL\fR
Open an irc://server:port/channel URL
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information

