PROG = conspire-bot
SRCS = conspire-bot.c
MAN  = conspire-bot.1

include ../../buildsys.mk
include ../../extra.mk

CPPFLAGS += -I../.. $(COMMON_CFLAGS)

LIBS += -L../common -lconspire $(COMMON_LIBS)

