STATIC_LIB_NOINST = libcontrast.a
LIB_MAJOR=0
LIB_MINOR=1

SRCS = contrast.c

include ../../buildsys.mk
include ../../extra.mk

CPPFLAGS += $(COMMON_CFLAGS) $(GUI_CFLAGS) -I../.. -I../../common
CFLAGS += $(LIB_CFLAGS)
LIBS += $(COMMON_LIBS)
