include ../../extra.mk

LIB = ${LIB_PREFIX}conspire-xchatemu${LIB_SUFFIX}
LIB_MAJOR=0
LIB_MINOR=1

SRCS = xchatemu.c

INCLUDES = xchatemu.h

include ../../buildsys.mk
include ../../extra.mk

CPPFLAGS += $(COMMON_CFLAGS)
CFLAGS += $(PLUGIN_CFLAGS)
LIBS += $(COMMON_LIBS)
