DATA = 	book.png		\
	balloon.png 		\
	conspire.png		\
	fileoffer.png		\
	hop.png			\
	op.png			\
	purple.png		\
	red.png			\
	voice.png		\
	channel.png		\
	server.png		\
	util.png		\
	dialog.png

include ../../buildsys.mk

PACKAGE = conspire/pixmaps


