LOCALES = be.po \
	  ca.po \
	  cs.po \
	  de.po \
	  el.po \
	  es.po \
	  fi.po \
	  fr.po \
	  gl.po \
	  hu.po \
	  it.po \
	  ja.po \
	  ko.po \
	  lt.po \
	  mk.po \
	  nl.po \
	  pa.po \
	  pt.po \
	  ru.po \
	  sq.po \
	  sr.po \
	  sv.po \
	  uk.po \
	  vi.po \
	  zh_CN.po \
	  zh_TW.po

include ../buildsys.mk
